print("wake up at 6:00am")
print("brush teeth")      
print("take bath")
print("go to school at 7:50am")
print("eat breakfast at 12:00am")
print("leave school at 3:00pm")
print("eat lunch")
print("play badminton")
print("study")
print("eat dinner at 8:00am")
print("sleep at 9:30am")
print("nighttime 1 hour study")
print("1*7 study hours")